### PR TITLE
pull request for including exact deflation part

### PR DESCRIPTION
**Pull request by marcuspetschlies**

### CODE REVIEW

**Comment by urbach** [comment]
ehh, should this be a pull request to etmc/tmLQCD ?

and how to review this...

**Comment by urbach** [comment]
so, what to do with this pull request? I'd like to close it as it should go to etmc/tmLQCD

**Comment by marcuspetschlies** [comment]
Sorry, can I undo it in some way?

Am 25.05.2016 um 11:37 schrieb Carsten Urbach:

**Comment by urbach** [comment]
I'll close it...

**Pull request closed without merging**
