### PR TITLE
Mybranch

### PR DESCRIPTION
**Pull request by marcuspetschlies**
changes in include/tmLQCD.h

### CODE REVIEW

**Comment by kostrzewa** [comment]
@marcuspetschlies 
Could we move this pull-request to etmc/master please? That way, the DDalphaAMG stuff will not distract from the important changes. Cheers!

**Comment by urbach** [comment]
@kostrzewa @marcuspetschlies I have merged etmc/master into my master. This should help a bit.

**Comment by urbach** [comment]
still, it would be better to have this pull request going to etmc/master

**Comment by marcuspetschlies** [comment]
Okay, ich werde versuchen, das nochmal zu machen.

**Comment by urbach** [comment]
now in etmc/master

**Pull request closed without merging**
